CREATE_PLAYER_MENU = 0  # Меню создания игрока
CREATE_SPACESHIP_MENU = 1

MAIN_MENU = 2  # Главное меню

INVENTORY = 3  # Инвентарь
INVENTORY_INFO = 4

PLAYER_PROFILE = 5  # Профиль игрока

EQUIPMENT = 6  # Меню снаряжения
EQUIPMENT_WEAPON_INFO = 7
EQUIPMENT_ARMOR_INFO = 8

FIGHT_SYSTEM = 9  # Боевая система
FIGHT_SYSTEM_PLAYER_TURN = 10
FIGHT_SYSTEM_WEAPON_USE = 11
FIGHT_SYSTEM_AIM_SHOT_MENU = 12

CABIN = 13  # Локация "Космический корабль"
CAPTAIN_BRIDGE = 14
CARGO_HOLD = 15
COMPUTER = 16

ESTRAD_PORT = 17  # Локация "Эстрад"
ESTRAD_SECURITY_SOLDIER = 18

ESTRAD_COLONY = 19  # Локация "Эстрад.Колония"
ESTRAD_BAR = 20
ESTRAD_TRADER = 21
ESTRAD_TRADER_TRADE_MENU = 22
ESTRAD_TRADER_BUY = 23
ESTRAD_TRADER_SELL = 24

ESTRAD_FOREST_ENTRY = 25  # Локация "Эстрад.Лес"
ESTRAD_FOREST_FIELD = 26
ESTRAD_FOREST_LAKE = 27
